name: chess-distance-py
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytest
  - pytest-asyncio
  - asyncpg
  - psycopg
  - uvicorn
  - fastapi
  - pandas
  - python-dotenv
  - requests
  - pip:
    - python-chess
    - types-requests
